### ISSUE TITLE
Model Upgrades

### ISSUE THREAD

**Issue by C0mpy** [krokodilj/kits#5]
Predsednik odredi odgovorno lice (nekog stanara iz zgrade) i po potrebe instituciju
Odgovorno lice ili institucija mogu da odrede drugo odgovorno lice, tj. instituciju
Predsednik ili institucija mogu da angažuju firmu koja ce obraditi kvar
Angažovana firma može da odbije, angažuje novu firmu ili prosledi predracun, ukoliko odluci da ce kvar obrađivati
Predsednik moze da prihvati ponudu firme ili da angažuje drugu ukoliko smatra da je cena previsoka

**Comment by krokodilj** [comment]
cool

**Comment by C0mpy** [comment]
Issue will be edited when Boskov explains the model further
